# action.yml
name: 'run-tests-using-gradle'
description: 'Run tests with mysql and redis dependency using gradle  '
inputs:
  folder:  # path to folder where selenium test tasks are defined by build.gradle
    description: 'Which folder has the build.gradle'
    required: true
  tasks:  # list of tasks
    description: 'What gradle tasks to run'
    required: true
    default: 'testSanity'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
    AWS_SSM_PATH_PREFIX: ${{ secrets.AWS_SSM_PATH_PREFIX }}
  args:
    - ${{ inputs.folder}}
    - ${{ inputs.tasks }}
